import "./style/main.css"
import "./assets/git.svg"
import "./assets/linkedin.svg"
import "./assets/twitter.svg"
import "./assets/edit.svg"
import img from "./assets/man.jpg"
import img2 from "./assets/man-working.jpg"
